<?php

return [
	'title' => [
		'generic' => 'Forums',
		'index' => 'Forum Index',
		'forum' => '{forum}',
		'bonus_game' => 'Error',
	],
	'stats' => [
		'posts' => '{stats}{count}{/stats} post|{stats}{count}{/stats} posts',
		'threads' => '{stats}{count}{/stats} thread|{stats}{count}{/stats} threads',
		'posts_today' => 'Posts today: {stats}{count}{/stats}',
		'posts_hour' => 'Posts this hour: {stats}{count}{/stats}',
		'line' => '{posts} in {threads} | {posts_today} | {posts_hour}',
	],
	'action' => [
		'edit' => 'Edit Forum',
		'c3_edit' => 'Edit C3',
		'c3_results' => 'View Results',
		'c3_vote' => 'Vote',
		'c3_berry_panel' => 'Berry Panel',
		'mark_read' => 'Mark Forum Read',
		'mark_tagged_read' => 'Mark Tagged Threads Read',
		'new_thread' => 'New Thread',
		'new_tagged_thread' => 'New Tagged Thread',
		'link' => 'Link',
	],
	'mark_all_read' => 'Mark all forums read',
	'watched_threads' => 'Watched threads',
	'security_2fa' => '{title}SECURITY NOTICE{/title}You are a moderator for this forum. Two-factor authentication (2FA) is required for all moderators. You will not have moderation privileges until you {link}enable 2FA{/link}.',
	'viewing_tagged' => 'Currently only viewing threads tagged as {tag}.',
	'breadcrumbs' => [
		'index' => 'Forum Index',
		'tagged' => 'Tagged Threads',
	],
	'category' => [
		'forums' => 'Forums',
		'subforums' => 'Subforums',
	],
	'last_post_info' => '{user} on {date} ({link})',
	'forum' => [
		'threads' => 'Threads',
		'posts' => 'Posts',
		'last_post' => 'Last reply: ',
		'new_posts' => 'New posts',
		'new_posts_sub' => 'New posts in subforums',
		'no_new_posts' => 'No new posts',
		'no_description' => 'No Description',
		'moderated_by' => 'Moderated by:',
		'no_posts' => 'No Posts',
	],
	'threads' => [
		'title' => 'Thread title',
		'created' => 'Posted on',
		'replies' => 'Replies',
		'views' => 'Views',
		'last_post' => 'Last reply',
		'no_replies' => 'No Replies',
		'status' => [
			'open' => 'No new posts',
			'closed' => 'Thread closed',
			'moved' => 'Phantom thread',
			'open_new' => 'New posts',
			'closed_new' => 'Thread closed, new posts',
			'moved_new' => 'New posts',
			'nsfw' => 'Not safe for work',
			'watched' => 'You\'re watching this thread',
		],
		'poll' => 'poll',
		'first_unread' => 'First Unread Reply',
		'view_latest' => 'View',
		'posted_by' => 'By {user} on {date}',
		'moved' => '[0] → Moved to {forum} (this will vanish from here soon)|[1]→ Moved to {forum} (this will vanish from here in a day)|[*,*]→ Moved to {forum} (this will vanish from here in {count} days)', // U+2192 (RIGHTWARDS ARROW)
		'page' => 'Page',
		'none' => 'There are no threads in this forum.',
	],
	'not_found' => [
		'title' => 'Error',
		'message' => 'The requested forum either does not exist or you don\'t have permission to view it.',
	],
	'bad_token' => [
		'title' => 'Error',
		'message' => 'Incorrect token.',
	],
	'read_all' => [
		'title' => 'Success',
		'message' => 'All forums have been marked read.',
	],
	'read_forum' => [
		'title' => 'Success',
		'message' => '{bold}{forum}{/bold} has been marked read.',
	],
	'read_tag_success' => [
		'title' => 'Success',
		'message' => 'All threads tagged {bold}{tag}{/bold} have been marked read.',
	],
	'read_tag_error' => [
		'title' => 'Error',
		'message' => 'The tag couldn\'t be marked read.',
	],
];
