<?php

return [
	'user_bar' => [
		'login' => 'Log In',
		'register' => 'Sign Up',
		'pm' => 'Private Messages',
		'pm_count' => '[0]{icon_empty}|[*,*]{icon}{new}{count} new{/new}',
		'notifications' => 'Notifications',
		'notifications_count' => '[0]{icon_empty}|[*,*]{icon}{new}{count} new{/new}',
		'user' => 'User Menu',
		'staff' => 'Staff Menu',
		'search' => 'Search…', // U+2026 (HORIZONTAL ELLIPSIS)
		'go' => 'Go',
		'language' => 'Language…', // U+2026 (HORIZONTAL ELLIPSIS)
	],
	'user_menu' => [
		'profile' => 'Profile',
		'files' => 'My Files',
		'editprofile' => 'Edit Profile',
		'logout' => 'Log Out',
	],
	'staff_menu' => [
		'staffpanel' => 'Staff Panel',
		'settings' => 'Settings',
		'staff_forum' => 'Staff Forum',
		'cloud' => 'Nextcloud',
		'sauron' => 'Sauron',
		'infractions' => 'Infractions',
		'ipbans' => 'IP Bans',
		'authlog' => 'Auth Log',
		'onlineusers' => 'Online Users',
	],
	'menu' => [
		'title' => 'Menu',
		'site' => [
			'name' => 'SMW Central',
			'main' => 'Main Page',
			'news' => 'News',
			'forums' => 'Forums',
			'member_list' => 'Member List',
			'rules' => 'Rules',
			'hall_of_fame' => 'Hall of Fame',
			'discord' => 'Discord',
			'about' => 'About Us',
			'staff' => 'Staff Team',
		],
		'common' => [
			'name' => 'Help & Resources',
			'beginners' => 'Beginners\' Guide',
			'guidelines' => 'Submission Guidelines',
			'glossary' => 'Glossary',
			'faq' => 'F.A.Q.',
			'tutorials' => 'Tutorials',
			'documents' => 'Documents',
			'tools' => 'Tools',
			'online_tools' => 'Online Tools',
			'sram' => 'SRAM Database',
		],
		'smw' => [
			'name' => 'Super Mario World',
			'hacks' => 'Hacks',
			'subforum' => 'Forum',
			'graphics' => 'Graphics',
			'music' => 'Music',
			'brrsamples' => 'BRR Samples',
			'blocks' => 'Blocks',
			'sprites' => 'Sprites',
			'tweaks' => 'Tweaks',
			'patches' => 'Patches',
			'uberasm' => 'UberASM',
			'rom_map' => 'ROM Map',
			'ram_map' => 'RAM Map',
			'hijack_map' => 'Hijack Map',
		],
		'yi' => [
			'name' => 'Yoshi\'s Island',
			'hacks' => 'Hacks',
			'subforum' => 'Forum',
			'music' => 'Music',
			'patches' => 'Patches',
			'spasm' => 'SPASM',
			'rom_map' => 'ROM Map',
			'ram_map' => 'RAM Map',
			'sram_map' => 'SRAM Map',
		],
		'sm64' => [
			'name' => 'Super Mario 64',
			'hacks' => 'Hacks',
			'subforum' => 'Forum',
			'music' => 'Music',
			'textures' => 'Textures',
			'documents' => 'Documents',
			'rom_map' => 'ROM Map',
			'ram_map' => 'RAM Map',
		],
		'unread' => "[1] \u{A0}- {new}new{/new}|[*,*] \u{A0}- {new}{count} new{/new}", // \u{A0} is U+00A0 (NO-BREAK SPACE)
	],
	'header' => [
		'image_info' => [
			'unknown' => 'From {source}',
			'authors' => '{authors} {br}({source})',
			'level' => '{level} {br}({source})',
			'authors_level' => '{level} by {authors} {br}({source})',
		],
		'users' => 'Users: {stats}{count}{/stats}',
		'active_users' => '({count} active)',
		'latest_user' => 'Latest user: {user}',
		'latest_user_hidden' => 'Latest user hidden',
	],
	'footer' => [
		'page_views' => 'Views: {stats}{count}{/stats}',
		'legal_information' => 'Legal Information',
		'privacy_policy' => 'Privacy Policy',
		'staff_comment' => 'Leave Feedback',
		'news' => 'News',
		'faq' => 'F. A. Q.',
		'about' => 'About Us',
		'forums' => 'Forums',
		'affiliates' => 'Affiliates',
		'open_source' => 'Open Source',
		'terms' => 'Terms of Service',
		'queries' => 'Queries: ~ {stats}{count}{/stats} ({stats}{time}{/stats} ms)',
		'generate_sql_report' => 'Generate SQL Report',
		'sql_report' => 'SQL Report',
		'execution_time' => 'Execution time: ~ {stats}{time}{/stats} ms (~ {stats}{memory}{/stats} peak memory)',
	],
	'online_user_list' => [
		'online' => '{stats}{count}{/stats} user online:|{stats}{count}{/stats} users online:',
		'hidden' => '{stats}{count}{/stats} user online ({stats}{hidden}{/stats} hidden):|{stats}{count}{/stats} users online ({stats}{hidden}{/stats} hidden):',
		'user_separator' => ', ',
		'guests' => 'Guests: {stats}{count}{/stats}',
		'stat_separator' => ' - ',
		'bots' => 'Bots: {stats}{count}{/stats}',
	],
	'pagination' => [
		'title' => 'Pages:',
		'range' => '{start}–{end}', // U+2013 (EN DASH)
		'asc' => 'Ascending',
		'desc' => 'Descending',
	],
	'post' => [
		'info' => [
			'generic' => 'Posted on {datetime}',
			'thread' => 'Posted on {datetime} in {thread}',
			'recipient' => 'Sent on {datetime} to {username}',
		],
		'unread' => 'NEW',
		'separator' => [
			'info' => ' - ',
			'menu' => ' | ',
		],
		'edited' => 'Last edited on {datetime} by {username}',
	],
	'post_sidebar' => [
		'last_seen' => [
			'online' => 'Online',
			'never' => 'Never',
		],
		'avatar' => 'Avatar',
		'info' => [
			'total_posts' => 'Posts: {stats}{count}{/stats}',
			'posts' => 'Posts: {stats}{count}/{total}{/stats}',
			'since' => 'Since: {stats}{datetime}{/stats}',
			'from' => 'From: {stats}{location}{/stats}',
			'pronouns' => 'Pronouns: {stats}{pronouns}{/stats}',
			'last_seen' => 'Last seen: {stats}{time}{/stats}',
			'last_warning' => 'Last infraction: {link}{time}{/link}',
		],
	],
	'qp_menu' => [
		'title' => 'Punishment',
		'notice' => 'Notice',
		'warn' => 'Warn',
		'ban' => 'Temp ban',
		'forumBan' => 'Forum ban',
		'sectionBan' => 'Section ban',
		'disable' => 'Disable',
		'nuke' => 'Nuke profile fields',
		'kamikaze' => 'Kamikaze',
	],
	'secondary_menu' => [
		'toggle' => 'Toggle menu',
	],
	'form' => [
		'horizontal' => [
			'title' => '{Title}',
			'description' => '{Description}',
		],
		'vertical' => [
			'title' => '{Title}: ',
			'label' => '{Title}',
		],
	],
];
